"""P7 report step: formatting helpers and the template renderer on small hand examples; the key numbers against
figures worked by hand from verbatim copies of the pipeline's output (tests/fixtures/report, D-008)."""
import math
from pathlib import Path

import pytest

from src import config
from src.report import numbers, render
from src.report.numbers import MINUS, ReportError

FX = Path(__file__).parent / "fixtures" / "report"


@pytest.fixture(scope="module")
def frames():
    return numbers.load(FX / "analysis", FX / "metrics", FX / "reference")


@pytest.fixture(scope="module")
def values(frames):
    return numbers.key_numbers(frames)


# ---------- formatting

def test_num_uses_real_minus_and_never_prints_negative_zero():
    assert numbers.num(-1.567) == MINUS + "1.57"
    assert numbers.num(-0.004) == "0.00"
    assert numbers.signed(0.2204) == "+0.22" and numbers.signed(-0.004) == "0.00"


def test_pct_converts_fraction_to_percent_number():
    assert numbers.pct(0.0157) == "1.57"
    assert numbers.spct(-0.0157123) == MINUS + "1.57" and numbers.spct(0.049036) == "+4.90"


def test_indian_grouping():
    assert numbers.indian(999) == "999" and numbers.indian(1000) == "1,000"
    assert numbers.indian(123456.7) == "1,23,457"
    assert numbers.indian(-1234567.891, 2) == MINUS + "12,34,567.89"
    assert numbers.indian(184493.4) == "1,84,493"


def test_t_stat_is_information_ratio_times_root_years():
    assert numbers.t_stat(0.5, 252 * 4) == pytest.approx(1.0)        # 4 years -> x2
    assert numbers.t_stat(-0.614793, 491) == pytest.approx(-0.614793 * math.sqrt(491 / 252))


def test_rank_phrase_and_names():
    assert numbers.rank_phrase(1, 17) == "the lowest of the 17"
    assert numbers.rank_phrase(2, 17) == "the 2nd lowest of the 17" and numbers.rank_phrase(11, 17) == "the 11th lowest of the 17"
    assert numbers.names(["A"]) == "A" and numbers.names(["A", "B", "C"]) == "A, B and C"


# ---------- renderer

def test_render_fills_placeholders():
    assert render.render("a {{x}} b {{ y }} {{x}}", {"x": "1", "y": "2"}) == "a 1 b 2 1"


def test_render_stops_on_unknown_placeholder():
    with pytest.raises(ReportError, match="made_up"):
        render.render("value {{made_up}}", {"x": "1"})


def test_render_stops_on_malformed_placeholder():
    with pytest.raises(ReportError, match="malformed"):
        render.render("value {{Bad Name}}", {"x": "1"})


def test_run_writes_title_then_banner(tmp_path):
    (tmp_path / "t.md").write_text("# Title\n\nbody {{x}}\n", encoding="utf-8")
    out = render.run(templates=tmp_path, targets={"t.md": tmp_path / "out" / "t.md"}, values={"x": "7"})
    text = out["t.md"].read_text(encoding="utf-8").splitlines()
    assert text[0] == "# Title" and text[1] == "" and text[2].startswith("<!-- Generated by") and text[-1] == "body 7"


def test_run_stops_when_template_missing(tmp_path):
    with pytest.raises(ReportError, match="template missing"):
        render.run(templates=tmp_path, targets={"nope.md": tmp_path / "nope.md"}, values={})


# ---------- key numbers, worked by hand from the fixture files

def test_counts(values):
    assert (values["n_universe_active"], values["n_eligible"], values["n_classified"], values["n_not_classified"]) == ("35", "32", "17", "15")
    assert (values["n_closet"], values["n_under"], values["n_low"], values["n_active"]) == ("9", "1", "10", "7")


def test_flagged_fund_figures(values):
    assert values["flag_fund"] == "UTI Large Cap"
    assert values["flag_xs_reg_24"] == MINUS + "1.57" and values["flag_xs_dir_24"] == MINUS + "0.78"
    assert values["flag_t"] == MINUS + "0.86"                      # -0.614793 x sqrt(491/252) = -0.8582
    assert values["flag_vs_index_fund"] == MINUS + "0.91"          # -1.5712 - (-0.6630)
    assert values["flag_neg12_windows"] == "18"                    # 0.75 x 24
    assert values["flag_fee_per_active"] == "3.4"                  # 1.1584 / 0.3427
    assert values["flag_overlap"] == "66" and values["flag_agree"] == "30"
    assert values["flag_rank_phrase"] == "the lowest of the 17"


def test_asset_and_fee_totals(values):
    # regular AAUM, Rs lakh: 10 funds below 0.40 sum to 1,84,49,340.42; 7 above to 86,23,969.68
    assert values["low_aaum_cr"] == "1,84,493" and values["classified_aaum_cr"] == "2,70,733"
    assert values["low_aaum_share"] == "68"                        # 18449340.42 / 27073310.10 = 68.1%
    assert values["low_cr"] == "1,783"                             # 1654.80 + 128.04
    assert values["classified_cr"] == "2,664"                      # + 880.91
    assert (values["low_fee_min"], values["low_fee_max"]) == ("0.83", "1.47")


def test_index_fund_and_significance(values):
    assert values["index_fund"] == "Bandhan Nifty 100 Index Fund"
    assert values["index_lag_reg"] == "0.66" and values["index_te_dir"] == "0.03"
    assert values["n_below_index_fund"] == "2" and values["below_index_fund_funds"] == "UTI Large Cap and Sundaram Large Cap"
    assert values["n_significant"] == "1" and values["significant_funds"] == "Motilal Oswal Large Cap"
    assert values["significant_t"] == "+2.10"                      # 1.505080 x 1.39586


def test_threshold_and_sensitivity(values):
    assert (values["threshold"], values["band_low"], values["band_high"]) == ("0.40", "0.369", "0.433")
    assert values["n_as_under_060"] == "16" and values["n_as_under_050"] == "15"
    assert values["sens_040_12m"] == "7 truly active, 2 closet, 8 closet and underperforming"
    assert values["equity_only_note"] == "the equity-only definition gives the same counts"
    assert values["fund_table"].count("\n") == 18                  # header + rule + 17 funds
    assert values["sensitivity_table"].count("\n") == 16           # header + rule + 15 variants


# ---------- guards: the templates' prose depends on these facts, so a change must stop the build

def test_stops_if_flagged_fund_count_changes(frames):
    f = dict(frames)
    c = f["cls"].copy()
    c.loc[c.fund_id == "sundaram_lc", "class_main"] = "closet_underperforming"
    f["cls"] = c
    with pytest.raises(ReportError, match="exactly one"):
        numbers.key_numbers(f)


def test_stops_if_class_summary_disagrees(frames):
    f = dict(frames)
    s = f["summary"].copy()
    s.loc[s.class_main == "closet", "funds"] = 8
    f["summary"] = s
    with pytest.raises(ReportError, match="disagree"):
        numbers.key_numbers(f)


def test_stops_if_index_fund_no_longer_trails(frames):
    f = dict(frames)
    r = f["rolling"].copy()
    r.loc[(r.fund_id == "bandhan_n100") & (r.plan == "regular"), "excess_ann"] = 0.001
    f["rolling"] = r
    with pytest.raises(ReportError, match="no longer"):
        numbers.key_numbers(f)


def test_load_names_missing_inputs(tmp_path):
    with pytest.raises(ReportError, match="fund_classification.csv"):
        numbers.load(tmp_path, tmp_path, tmp_path)


# ---------- templates

@pytest.mark.parametrize("name", sorted(render.TARGETS))
def test_every_template_renders_with_pipeline_numbers(name, values):
    text = render.render((render.TEMPLATES / name).read_text(encoding="utf-8"), values)
    assert "{{" not in text and text.startswith("# ")


@pytest.mark.parametrize("name", sorted(render.TARGETS))
def test_committed_documents_have_no_unfilled_placeholders(name):
    target = render.TARGETS[name]
    assert target.exists(), f"{target.relative_to(config.ROOT)} missing: run `python run_pipeline.py report --offline`"
    assert "{{" not in target.read_text(encoding="utf-8")


def test_memo_fits_two_pages(values):
    memo = render.render((render.TEMPLATES / "memo.md").read_text(encoding="utf-8"), values)
    assert len(memo.split("## Fund-level results")[0].split()) <= 850   # prose budget; the table adds 17 rows
