"""Fill the document templates in reports/templates/ with the pipeline's numbers (D-059).

    python run_pipeline.py report --offline

A template refers to a figure as {{name}}. An unknown name stops the build; nothing is ever left blank.
"""
from __future__ import annotations

import re
from pathlib import Path

from src import config
from src.report import numbers

TEMPLATES = config.ROOT / "reports" / "templates"
TARGETS = {"memo.md": config.ROOT / "reports" / "memo.md", "README.md": config.ROOT / "README.md",
           "interview_defense.md": config.DOCS / "interview_defense.md", "resume_bullets.md": config.DOCS / "resume_bullets.md"}
PLACEHOLDER = re.compile(r"\{\{\s*([a-z0-9_]+)\s*\}\}")
BANNER = "<!-- Generated by `python run_pipeline.py report` from reports/templates/{name}. Edit the template, not this file. -->\n"


def placeholders(text: str) -> list[str]:
    return PLACEHOLDER.findall(text)


def render(text: str, values: dict[str, str]) -> str:
    unknown = sorted({k for k in placeholders(text) if k not in values})
    if unknown:
        raise numbers.ReportError(f"template uses figures the pipeline does not provide: {unknown}")
    out = PLACEHOLDER.sub(lambda m: values[m.group(1)], text)
    if "{{" in out or "}}" in out:
        raise numbers.ReportError("malformed placeholder left in the rendered text")
    return out


def run(templates: Path = TEMPLATES, targets: dict[str, Path] | None = None, values: dict[str, str] | None = None) -> dict[str, Path]:
    targets = TARGETS if targets is None else targets
    values = numbers.key_numbers(numbers.load()) if values is None else values
    written = {}
    for name, target in targets.items():
        src = templates / name
        if not src.exists():
            raise numbers.ReportError(f"template missing: {src}")
        text = render(src.read_text(encoding="utf-8"), values)
        title, sep, rest = text.partition("\n")          # keep the H1 on line 1 so GitHub shows a title
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(title + sep + "\n" + BANNER.format(name=name) + rest, encoding="utf-8", newline="\n")
        written[name] = target
    return written
